name:  gol_grid
description: A widget showing a controllable square grid of cellular automata.
version: 0.2.0
homepage: https://github.com/monopole/gol_grid

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  grid_world: ^2.0.0
  meta: ^1.7.0
  thumper: ^2.2.0

dev_dependencies:
  test: ^1.20.2
  lints: ^1.0.1

flutter:
  uses-material-design: true
